// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJHS7EdbofXmGRfgHGOPhb5rDqt24zbmc',
    appId: '1:350474803175:web:883c58746a8e1bdec08f42',
    messagingSenderId: '350474803175',
    projectId: 'goindia-44ea7',
    authDomain: 'goindia-44ea7.firebaseapp.com',
    storageBucket: 'goindia-44ea7.firebasestorage.app',
    measurementId: 'G-RPX4FP72PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALNJltc3Leg3TNNXDPTdDuygoYdXvcGQs',
    appId: '1:350474803175:android:c8248a4136d62d15c08f42',
    messagingSenderId: '350474803175',
    projectId: 'goindia-44ea7',
    storageBucket: 'goindia-44ea7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_QQwSHiZWf52HdoxoAq9TMSol0pgFkdc',
    appId: '1:350474803175:ios:cfd3a028e08ae94cc08f42',
    messagingSenderId: '350474803175',
    projectId: 'goindia-44ea7',
    storageBucket: 'goindia-44ea7.firebasestorage.app',
    iosBundleId: 'com.example.goindiann',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_QQwSHiZWf52HdoxoAq9TMSol0pgFkdc',
    appId: '1:350474803175:ios:cfd3a028e08ae94cc08f42',
    messagingSenderId: '350474803175',
    projectId: 'goindia-44ea7',
    storageBucket: 'goindia-44ea7.firebasestorage.app',
    iosBundleId: 'com.example.goindiann',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJHS7EdbofXmGRfgHGOPhb5rDqt24zbmc',
    appId: '1:350474803175:web:6cdbf85ae9119078c08f42',
    messagingSenderId: '350474803175',
    projectId: 'goindia-44ea7',
    authDomain: 'goindia-44ea7.firebaseapp.com',
    storageBucket: 'goindia-44ea7.firebasestorage.app',
    measurementId: 'G-ECM1ZGTJZM',
  );
}
